User.new(username: 'guest', password: 'guest', avatar_img: 'https://cdn.drawception.com/images/panels/2017/6-24/dWqG1O57LE-8.png').save
Deck.new(user_id: 1, name: 'Bant Nexus Control', color: '{U}{G}{W}', description: "Strategy: don't let your opponents play the game", gameFormat: 'Modern').save

Card.new(api_id: "c400307c-8bba-57bb-8ba9-20c531d1e0de",
cmc: 0,
colorIdentity: nil,
colors: nil,
deck_id: 1,
flavor: "Ships blown north in their voyage across the Stormwreck Sea become trapped in the unmelting ice.",
full_type: "Land",
gameFormat: nil,
id: 16,
imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=435416&type=card",
loyalty: nil,
manaCost: nil,
name: "Glacial Fortress",
power: nil,
quantity: 3,
rarity: "Rare",
set: "XLN",
subtypes: nil,
supertypes: nil,
text: "Glacial Fortress enters the battlefield tapped unless you control a Plains or an Island.↵{T}: Add {W} or {U}.",
toughness: nil,
types: nil,
).save

Card.new(
api_id: "e4e870c5-6bda-5e8c-9b3b-e36f6c2b0ac7",
cmc: 0,
colorIdentity: nil,
colors: nil,
deck_id: 1,
flavor: "One beginning, many paths.↵—Vannifar",
full_type: "Land — Forest Island",
gameFormat: nil,
id: 15,
imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=457390&type=card",
loyalty: nil,
manaCost: nil,
name: "Breeding Pool",
power: nil,
quantity: 4,
rarity: "Rare",
set: "RNA",
subtypes: nil,
supertypes: nil,
text: "({T}: Add {G} or {U}.)↵As Breeding Pool enters the battlefield, you may pay 2 life. If you don't, it enters the battlefield tapped.",
toughness: nil,
types: nil,
).save

Card.new(
api_id: "f53637c9-9f4e-5d3c-a11a-c30e8e9a92b4",
cmc: 0,
colorIdentity: nil,
colors: nil,
deck_id: 1,
flavor: nil,
full_type: "Basic Land — Forest",
gameFormat: nil,
id: 2,
imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129559&type=card",
loyalty: nil,
manaCost: nil,
name: "Forest",
power: nil,
quantity: 1,
rarity: "Common",
set: "10E",
subtypes: nil,
supertypes: nil,
text: "({T}: Add {G}.)",
toughness: nil,
types: nil,
).save

Card.new(
api_id: "0d07714c-f700-5ed0-b354-9c9382bb0c5e",
cmc: 5,
colorIdentity: nil,
colors: nil,
deck_id: 1,
flavor: nil,
full_type: "Legendary Planeswalker — Teferi",
gameFormat: nil,
id: 3,
imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=443095&type=card",
loyalty: "4",
manaCost: "{3}{W}{U}",
name: "Teferi, Hero of Dominaria",
power: nil,
quantity: 3,
rarity: "Mythic",
set: "DOM",
subtypes: nil,
supertypes: nil,
text: "+1: Draw a card. At the beginning of the next end step, untap up to two lands.↵−3: Put target nonland permanent into its owner's library third from the top.↵−8: You get an emblem with 'Whenever you draw a card, exile target permanent an opponent controls.'",
toughness: nil,
types: nil,
).save

Card.new(
api_id: "0fd7e6b0-0fac-5354-934f-2e5f09c6b33c",
cmc: 2,
colorIdentity: nil,
colors: nil,
deck_id: 1,
flavor: "Cyclical and spiral patterns are the specialty of the Gyre Clade, which sees to revitalize the cycles of nature.",
full_type: "Instant",
gameFormat: nil,
id: 6,
imageUrl: nil,
loyalty: nil,
manaCost: "{G}{U}",
name: "Growth Spiral",
power: nil,
quantity: 4,
rarity: "Common",
set: "PRNA",
subtypes: nil,
supertypes: nil,
text: "Draw a card. You may put a land card from your hand onto the battlefield.",
toughness: nil,
types: nil,
).save

Card.new(
api_id: "c8a1498e-0e5b-5e06-b133-8a0344dac414",
cmc: 2,
colorIdentity: nil,
colors: nil,
deck_id: 1,
flavor: "The only casualties were a snapped spear, a lost helmet, and some bruised egos.",
full_type: "Instant",
gameFormat: nil,
id: 7,
imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=447335&type=card",
loyalty: nil,
manaCost: "{1}{G}",
name: "Root Snare",
power: nil,
quantity: 4,
rarity: "Common",
set: "M19",
subtypes: nil,
supertypes: nil,
text: "Prevent all combat damage that would be dealt this turn.",
toughness: nil,
types: nil,
).save

Card.new(
api_id: "c7e68041-3ef8-54c5-91a2-012fa711bbb0",
cmc: 4,
colorIdentity: nil,
colors: nil,
deck_id: 1,
flavor: "My specialty is theoretical universal limits and ways to circumvent them.",
full_type: "Instant",
gameFormat: nil,
id: 8,
imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=452782&type=card",
loyalty: nil,
manaCost: "{3}{U}",
name: "Chemister's Insight",
power: nil,
quantity: 3,
rarity: "Uncommon",
set: "GRN",
subtypes: nil,
supertypes: nil,
text: "Draw two cards.↵Jump-start (You may cast this card from your graveyard by discarding a card in addition to paying its other costs. Then exile this card.)",
toughness: nil,
types: nil,
).save

Card.new(
api_id: "f59b04c2-5037-5f6a-8e66-1f99079e7ae0",
cmc: 2,
colorIdentity: nil,
colors: nil,
deck_id: 1,
flavor: "The Sunken Ruin houses all the learning of a long-forgotten age.",
full_type: "Legendary Enchantment",
gameFormat: nil,
id: 9,
imageUrl: nil,
loyalty: nil,
manaCost: "{1}{U}",
name: "Search for Azcanta",
power: nil,
quantity: 3,
rarity: "Rare",
set: "PXLN",
subtypes: nil,
supertypes: nil,
text: "At the beginning of your upkeep, look at the top card of your library. You may put it into your graveyard. Then if you have seven or more cards in your graveyard, you may transform Search for Azcanta.",
toughness: nil,
types: nil,
).save

Card.new(
    api_id: "2c6b1134-b0ea-568e-ac6a-ed57bd5d7c94",
cmc: 4,
colorIdentity: nil,
colors: nil,
deck_id: 1,
flavor: "Walls crack. Buildings fall. Always the wilds return.↵—Domri Rade",
full_type: "Enchantment",
gameFormat: nil,
id: 12,
imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=457293&type=card",
loyalty: nil,
manaCost: "{3}{G}",
name: "Wilderness Reclamation",
power: nil,
quantity: 4,
rarity: "Uncommon",
set: "RNA",
subtypes: nil,
supertypes: nil,
text: "At the beginning of your end step, untap all lands you control.",
toughness: nil,
types: nil,
).save

Card.new(
    api_id: "4f1435b3-8cd7-5a8f-84b0-e057626dc911",
cmc: 6,
colorIdentity: nil,
colors: nil,
deck_id: 1,
flavor: nil,
full_type: "Instant",
gameFormat: nil,
id: 13,
imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=457369&type=card",
loyalty: nil,
manaCost: "{1}{W/U}",
name: "Depose",
power: nil,
quantity: 4,
rarity: "Uncommon",
set: "RNA",
subtypes: nil,
supertypes: nil,
text: "Tap target creature.↵Draw a card.",
toughness: nil,
types: nil,
).save

Card.new(
    api_id: "68dd6488-4482-5249-850f-45beb343c6ce",
cmc: 0,
colorIdentity: nil,
colors: nil,
deck_id: 1,
flavor: nil,
full_type: "Land",
gameFormat: nil,
id: 14,
imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=439849&type=card",
loyalty: nil,
manaCost: nil,
name: "Arch of Orazca",
power: nil,
quantity: 1,
rarity: "Rare",
set: "RIX",
subtypes: nil,
supertypes: nil,
text: "Ascend (If you control ten or more permanents, you get the city's blessing for the rest of the game.)↵{T}: Add {C}.↵{5}, {T}: Draw a card. Activate this ability only if you have the city's blessing.",
toughness: nil,
types: nil,
).save

Card.new(
    api_id: "ab6d408f-63db-57b6-9382-586cbceade42",
cmc: 7,
colorIdentity: nil,
colors: nil,
deck_id: 1,
flavor: "Sarkhan wandered into a tomb and back in time.",
full_type: "Instant",
gameFormat: nil,
id: 19,
imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=450253&type=card",
loyalty: nil,
manaCost: "{5}{U}{U}",
name: "Nexus of Fate",
power: nil,
quantity: 4,
rarity: "Mythic",
set: "M19",
subtypes: nil,
supertypes: nil,
text: "Take an extra turn after this one.↵If Nexus of Fate would be put into a graveyard from anywhere, reveal Nexus of Fate and shuffle it into its owner's library instead.",
toughness: nil,
types: nil,
).save

Card.new(
    api_id: "d1543033-66d4-514d-a0d7-607e199cae08",
cmc: 0,
colorIdentity: nil,
colors: nil,
deck_id: 1,
flavor: "Our ancestors brought down a Phyrexian portal ship, then built our town on its hull. We're pretty proud of that. —Alene of Riverspan",
full_type: "Land",
gameFormat: nil,
id: 21,
imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=443128&type=card",
loyalty: nil,
manaCost: nil,
name: "Hinterland Harbor",
power: nil,
quantity: 4,
rarity: "Rare",
set: "DOM",
subtypes: nil,
supertypes: nil,
text: "Hinterland Harbor enters the battlefield tapped unless you control a Forest or an Island.↵{T}: Add {G} or {U}.",
toughness: nil,
types: nil,
).save

Card.new(
    api_id: "f7a821d9-44d8-56e9-8c37-c86f27096e1f",
cmc: 0,
colorIdentity: nil,
colors: nil,
deck_id: 1,
flavor: nil,
full_type: "Basic Land — Island",
gameFormat: nil,
id: 24,
imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=129606&type=card",
loyalty: nil,
manaCost: nil,
name: "Island",
power: nil,
quantity: 1,
rarity: "Common",
set: "10E",
subtypes: nil,
supertypes: nil,
text: "({T}: Add {U}.)",
toughness: nil,
types: nil,
).save

Card.new(
api_id: "d30d04e9-9e75-5e5e-a580-bd502680a0eb",
cmc: 0,
colorIdentity: nil,
colors: nil,
deck_id: 1,
flavor: "To the Sun Empire, any place where daylight brightens the jungle floor is sacred ground.",
full_type: "Land",
gameFormat: nil,
id: 25,
imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=435418&type=card",
loyalty: nil,
manaCost: nil,
name: "Sunpetal Grove",
power: nil,
quantity: 4,
rarity: "Rare",
set: "XLN",
subtypes: nil,
supertypes: nil,
text: "Sunpetal Grove enters the battlefield tapped unless you control a Forest or a Plains.↵{T}: Add {G} or {W}.",
toughness: nil,
types: nil,
).save

Card.new(
    api_id: "373e4015-22b5-5ce7-a931-0904018dff9f",
    cmc: 0,
    colorIdentity: nil,
    colors: nil,
    deck_id: 1,
    flavor: "Where the roots reach, there the temple rises.↵'—Niszka, Selesnya evangel'",
    full_type: "Land — Forest Plains",
    gameFormat: nil,
    id: 27,
    imageUrl: "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=453008&type=card",
    loyalty: nil,
    manaCost: nil,
    name: "Temple Garden",
    power: nil,
    quantity: 4,
    rarity: "Rare",
    set: "GRN",
    subtypes: nil,
    supertypes: nil,
    text: "({T}: Add {G} or {W}.)↵As Temple Garden enters the battlefield, you may pay 2 life. If you don't, it enters the battlefield tapped.",
    toughness: nil,
    types: nil,
).save